### ISSUE TITLE
How do I get non-HTML encoded output?

### ISSUE THREAD

**Issue by piascikj** [jaredwray/ecto#25]
I'm running ecto with the following code  and it's producing  html encoded output.  Is there any way to force non-encoded?

```js
...
(async () => {
  const filePath = _path.join(this.project.path, path)
  const engineName = this.ecto.getEngineByFilePath(filePath)
  try {
    const source = await fs.promises.readFile(filePath, "utf8")
    const content = await this.ecto.render(source, {path: this.project.path, lists: this.project.lists}, engineName)
    this.project.copyToClipboard(content, `${name} copied to clipboard!`)
  } catch (err) {
    console.log(`Error copying ${name} to clipboard`, err)
  }
})()
...
```

The template...
```mustache
# {{path}}

{{#lists}}
## {{name}}
{{/lists}}
```

The output...
```
# /Users/jesse/projects/imdone-plugins-dev

## What&#x27;s Due?
## NOTE
## TODO
## DOING
## DONE
## Recently Completed
```

**Comment by jaredwray** [comment]
@piascikj - by default it does do html encoding. One thing you could do us un-encode it after it is rendered. I can also look at a way to remove the html encoding if needed but it would take longer.

**Comment by jaredwray** [comment]
@piascikj - fix should be done and released today. Closing this down so we do not do the escape anymore.

**Comment by jaredwray** [comment]
@piascikj this should be fixed on the latest release. https://github.com/jaredwray/ecto/releases/tag/v1.1.3
