### ISSUE TITLE
Can't install with pnpm

### ISSUE THREAD

**Issue by frog-o** [jaredwray/ecto#69]
When i trying install ecto with 

pnpm install ecto

i get this error

pnpm: Command failed with exit code 128: /usr/bin/git ls-remote git+ssh://git@github.com/jaredwray/helpers-for-handlebars.git HEAD
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Do you have any idea how i can fix this problem?

**Comment by jaredwray** [comment]
@frog-o - sorry for the delay on this and it has been fixed.

**Comment by frog-o** [comment]
Thanks i have no problem with delays especially since work keeps me busy
and going to be a while to see if your fix works for me i appreciate it 😊.
